export const FETCH_TENANTS_REQUEST = "FETCH_TENANTS_REQUEST";
export const FETCH_TENANTS_SUCCESS = "FETCH_TENANTS_SUCCESS";
export const FETCH_ADD_TENANT_SUCCESS = "FETCH_ADD_TENANT_SUCCESS";
export const FETCH_DELETE_TENANT_SUCCESS = "FETCH_DELETE_TENANT_SUCCESS";
export const FETCH_EDIT_TENANT_SUCCESS = "FETCH_EDIT_TENANT_SUCCESS";
export const FETCH_TENANTS_FAILURE = "FETCH_TENANTS_FAILURE";
export const FETCH_GET_TENANTS_FAILURE = "FETCH_GET_TENANTS_FAILURE";
export const FETCH_INIT_EDIT_TENANT = "FETCH_INIT_EDIT_TENANT"