export const FETCH_GET_ALL_EMPLOYEES_REQUEST = "FETCH_GET_ALL_EMPLOYEES_REQUEST";
export const FETCH_GET_ALL_EMPLOYEES_SUCCESS = "FETCH_GET_ALL_EMPLOYEES_SUCCESS";   
export const FETCH_GET_ALL_EMPLOYEES_FAILURE = "FETCH_GET_ALL_EMPLOYEES_FAILURE";
export const FETCH_ADD_EMPLOYEE_FAILURE = "FETCH_ADD_EMPLOYEE_FAILURE";
export const FETCH_ADD_EMPLOYEE = "FETCH_ADD_EMPLOYEE";
export const FETCH_EDIT_EMPLOYEE = "FETCH_EDIT_EMPLOYEE";
export const FETCH_INIT_EDIT_EMPLOYEE = "FETCH_INIT_EDIT_EMPLOYEE";
