export const FETCH_ADMINS_REQUEST = "FETCH_ADMINS_REQUEST";
export const FETCH_ADMINS_SUCCESS = "FETCH_ADMINS_SUCCESS";
export const FETCH_ADD_ADMIN_SUCCESS = "FETCH_ADD_ADMIN_SUCCESS";
export const FETCH_DELETE_ADMIN_SUCCESS = "FETCH_DELETE_ADMIN_SUCCESS";
export const FETCH_EDIT_ADMIN_SUCCESS = "FETCH_EDIT_ADMIN_SUCCESS";
export const FETCH_ADMINS_FAILURE = "FETCH_ADMINS_FAILURE";
export const FETCH_GET_ADMINS_FAILURE = "FETCH_GET_ADMINS_FAILURE";
export const FETCH_INIT_EDIT_ADMIN = "FETCH_INIT_EDIT_ADMIN"