export const FETCH_GET_ALL_DISPLAYS_REQUEST = "FETCH_GET_ALL_DISPLAYS_REQUEST";
export const FETCH_GET_ALL_DISPLAYS_SUCCESS = "FETCH_GET_ALL_DISPLAYS_SUCCESS";   
export const FETCH_GET_ALL_DISPLAYS_FAILURE = "FETCH_GET_ALL_DISPLAYS_FAILURE";
export const FETCH_EDIT_DISPLAYS = "FETCH_EDIT_DISPLAYS";
export const FETCH_EDIT_DISPLAY = "FETCH_EDIT_DISPLAY";
export const FETCH_EDIT_DISPLAYS_FAILURE = "FETCH_EDIT_DISPLAYS_FAILURE";
