export const FETCH_GET_ALL_RESPONSES_REQUEST = "FETCH_GET_ALL_RESPONSES_REQUEST";
export const FETCH_GET_ALL_RESPONSES_SUCCESS = "FETCH_GET_ALL_RESPONSES_SUCCESS";   
export const FETCH_GET_ALL_RESPONSES_FAILURE = "FETCH_GET_ALL_RESPONSES_FAILURE";
export const FETCH_ADD_RESPONSE_FAILURE = "FETCH_ADD_RESPONSE_FAILURE";
export const FETCH_EDIT_RESPONSE = "FETCH_EDIT_RESPONSE";
export const FETCH_EDIT_RESPONSE_FAILURE = "FETCH_EDIT_RESPONSE_FAILURE";
